### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [SpadeLiu/Graft-PSMNet#1]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

https://github.com/PINTO0309/PINTO_model_zoo

- feature extractor + adaptor + aggregator, all merged End-to-End onnx
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/292_Graft-PSMNet

**Comment by SpadeLiu** [comment]
The license file has been uploaded.

**Comment by PINTO0309** [comment]
Thank you!
