### ISSUE TITLE
Can your work be seen as a type of transfer learning? 

### ISSUE THREAD

**Issue by Zhaohuai-L** [SpadeLiu/Graft-PSMNet#5]
Hi,thank you very much for your great work，Can your work be seen as a type of transfer learning? 
The prior knowledge is that you think the StereoMatching(Pixelwise task) has the same low-level features as Classification,So Can it be regarded as transfer learning?

**Comment by SpadeLiu** [comment]
Hi,

Yes, please refer to "Learning Across Tasks and Domains", ICCV 2019. But in my opinion, I think most of the vision tasks share some same low-level features.

**Comment by Zhaohuai-L** [comment]
Okay,thanks.
