### ISSUE TITLE
supplementary materials in paper

### ISSUE THREAD

**Issue by Hyper-Devil** [SpadeLiu/Graft-PSMNet#8]
Thank you for your outstanding work.
Part of the analysis in the paper needs to refer to the supplementary materials, but I did not see the supplementary materials in the preprint and cvpr version. Can you give me some help? Thank you.

**Comment by SpadeLiu** [comment]
> 

Hi, 

Please give me your address and I will send an email to you.

**Comment by Hyper-Devil** [comment]
@SpadeLiu 
My email address is tywhd@qq.com , thank you for sharing.

**Comment by MaitaYuki** [comment]
@SpadeLiu ,

Could you please send your supplementary material to my email wendyengineer@gmail.com?

Thanks

**Comment by Hyper-Devil** [comment]
> @SpadeLiu ,
> 
> Could you please send your supplementary material to my email [wendyengineer@gmail.com](mailto:wendyengineer@gmail.com)?
> 
> Thanks

Hi,

Supplementary material is available here: https://openaccess.thecvf.com/content/CVPR2022/html/Liu_GraftNet_Towards_Domain_Generalized_Stereo_Matching_With_a_Broad-Spectrum_and_CVPR_2022_paper.html

“supp” at the bottom.
